import NavigationDrawerItem from "@/components/NavigationDrawer/NavigationDrawerItem";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: 'flex' }}>{children}</body>
    </html>
  );
}
